# This is a basic workflow to help you get started with Actions
  - name: onedrive-to-github-sync
  # You may pin to the exact commit or the version.
  # uses: BenjaminMichaelis/onedrive-to-github-sync-action@3b06ac26ddc9d2dce5601d9b2bb88dae3da1b644
  uses: BenjaminMichaelis/onedrive-to-github-sync-action@v0.0.1
  with:
    # Comma-seperated list of the share url of each file with ?download=1 appended
    urls: ["https://calkinsnetworks-my.sharepoint.com/:t:/g/personal/olenel_teligencepartners_com/ESPF3LVL2PZLlFnkqvYShVUBT--kwnII5paINVnvWh0NEw?e=CpEkdT?download=1"]
